"""user fields extra

Revision ID: 09dd798fb4ee
Revises: 79bd4e038f67
Create Date: 2024-10-26 10:52:56.918189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09dd798fb4ee'
down_revision: Union[str, None] = '79bd4e038f67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('app_username', sa.String(length=128), nullable=True))
    op.add_column('users', sa.Column('male', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('birth_date', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('is_onboarded', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_onboarded')
    op.drop_column('users', 'birth_date')
    op.drop_column('users', 'male')
    op.drop_column('users', 'app_username')
    # ### end Alembic commands ###
