"""terms

Revision ID: 1e89e80c211e
Revises: 2904f67058c9
Create Date: 2024-11-17 15:00:45.419685

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '1e89e80c211e'
down_revision: Union[str, None] = '2904f67058c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_terms_accepted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_terms_accepted')
    # ### end Alembic commands ###
