"""user model update

Revision ID: 251346e16d50
Revises: 10d9e7c0502c
Create Date: 2024-10-12 18:05:07.013341

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "251346e16d50"
down_revision: Union[str, None] = "10d9e7c0502c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("first_name", sa.String(length=64), nullable=False)
    )
    op.add_column("users", sa.Column("last_name", sa.String(length=64), nullable=True))
    op.add_column("users", sa.Column("is_bot", sa.Boolean(), nullable=True))
    op.add_column(
        "users", sa.Column("language_code", sa.String(length=8), nullable=True)
    )
    op.add_column("users", sa.Column("is_premium", sa.Boolean(), nullable=True))
    op.add_column(
        "users", sa.Column("added_to_attachment_menu", sa.Boolean(), nullable=True)
    )
    op.add_column("users", sa.Column("allows_write_to_pm", sa.Boolean(), nullable=True))
    op.add_column("users", sa.Column("photo_url", sa.String(length=255), nullable=True))
    op.alter_column(
        "users",
        "username",
        existing_type=sa.VARCHAR(length=128),
        type_=sa.String(length=32),
        existing_nullable=True,
    )
    op.drop_column("users", "full_name")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "full_name", sa.VARCHAR(length=128), autoincrement=False, nullable=False
        ),
    )
    op.alter_column(
        "users",
        "username",
        existing_type=sa.String(length=32),
        type_=sa.VARCHAR(length=128),
        existing_nullable=True,
    )
    op.drop_column("users", "photo_url")
    op.drop_column("users", "allows_write_to_pm")
    op.drop_column("users", "added_to_attachment_menu")
    op.drop_column("users", "is_premium")
    op.drop_column("users", "language_code")
    op.drop_column("users", "is_bot")
    op.drop_column("users", "last_name")
    op.drop_column("users", "first_name")
    # ### end Alembic commands ###
