"""app_language_code upd

Revision ID: 2904f67058c9
Revises: 9620fa1bcc91
Create Date: 2024-11-17 10:09:29.136258

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2904f67058c9'
down_revision: Union[str, None] = '9620fa1bcc91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'app_language_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'app_language_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
