"""friendships

Revision ID: 79bd4e038f67
Revises: 4d4d0dbf3c31
Create Date: 2024-10-21 22:06:21.952239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '79bd4e038f67'
down_revision: Union[str, None] = '4d4d0dbf3c31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quiz_responses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('taker_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('answer_id', sa.Integer(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['answer_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['taker_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('quizresponses')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quizresponses',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('taker_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('question_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('answer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['answer_id'], ['users.user_id'], name='quizresponses_answer_id_fkey'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name='quizresponses_question_id_fkey'),
    sa.ForeignKeyConstraint(['taker_id'], ['users.user_id'], name='quizresponses_taker_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='quizresponses_pkey')
    )
    op.drop_table('quiz_responses')
    # ### end Alembic commands ###
