"""tarot?

Revision ID: 8dd5c57c17a2
Revises: 16441da0835e
Create Date: 2024-11-13 06:55:24.591882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8dd5c57c17a2'
down_revision: Union[str, None] = '16441da0835e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quiz_responses')
    op.drop_table('questions')
    op.add_column('users', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    op.create_table('questions',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('questions_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('text', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('emoji', sa.VARCHAR(length=8), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='questions_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('quiz_responses',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('taker_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('question_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('answer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['answer_id'], ['users.user_id'], name='quiz_responses_answer_id_fkey'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name='quiz_responses_question_id_fkey'),
    sa.ForeignKeyConstraint(['taker_id'], ['users.user_id'], name='quiz_responses_taker_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='quiz_responses_pkey')
    )
    # ### end Alembic commands ###
