"""friendships

Revision ID: f8d34589dbe1
Revises: 6e9b8b859db2
Create Date: 2024-10-17 16:16:58.810722

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f8d34589dbe1'
down_revision: Union[str, None] = '6e9b8b859db2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friendships',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('user_id1', sa.BIGINT(), nullable=False),
    sa.Column('user_id2', sa.BIGINT(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id1'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['user_id2'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id1', 'user_id2', name='uq_friendship')
    )
    op.create_index(op.f('ix_friendships_user_id1'), 'friendships', ['user_id1'], unique=False)
    op.create_index(op.f('ix_friendships_user_id2'), 'friendships', ['user_id2'], unique=False)
    op.drop_column('questions', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_friendships_user_id2'), table_name='friendships')
    op.drop_index(op.f('ix_friendships_user_id1'), table_name='friendships')
    op.drop_table('friendships')
    # ### end Alembic commands ###
